### ISSUE TITLE
Examples need to be updated to reflect v0.2.0 changes in spec

### ISSUE THREAD

**Issue by frenchi** [openvex/examples#2]
_Reopening https://github.com/openvex/spec/issues/42 over here as it's more appropriate._

The recent [v0.2.0 release](https://github.com/openvex/spec/releases/tag/v0.2.0) introduced new enhancements to the spec, but while some examples were updated in [the original PR](https://github.com/openvex/spec/pull/35/files), some documentation has not been updated to reflect this.

Specific spec changes:

- [OPEV-0014: Expansion of the VEX Product Field](https://github.com/openvex/community/blob/main/enhancements/opev-0014.md),
- [OPEV-0015: Expansion of the Vulnerability Field](https://github.com/openvex/community/blob/main/enhancements/opev-0015.md),

I've started on a PR for the above, but opening this issue for discussion, in case there are any other references I've missed. Are there any other locations these should be updated?

**Comment by puerco** [comment]
This was fixed in #3
